src/Entity/Matiére.php
<?php

namespace App\Entity;

use App\Repository\MatiéreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MatiéreRepository::class)]
class Matiére
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_M = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $intitulé = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdM(): ?int
    {
        return $this->id_M;
    }

    public function setIdM(int $id_M): static
    {
        $this->id_M = $id_M;

        return $this;
    }

    public function getIntitulé(): ?string
    {
        return $this->intitulé;
    }

    public function setIntitulé(?string $intitulé): static
    {
        $this->intitulé = $intitulé;

        return $this;
    }
}

src/Form/MatiéreType.php
<?php

namespace App\Form;

use App\Entity\Matiére;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatiéreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_M')
            ->add('intitulé')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Matiére::class,
        ]);
    }
}

src/Controller/MatiéreController.php
<?php

namespace App\Controller;

use App\Entity\Matiére;
use App\Form\MatiéreType;
use App\Repository\MatiéreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/mati/re')]
class MatiéreController extends AbstractController
{
    #[Route('/', name: 'app_mati_re_index', methods: ['GET'])]
    public function index(MatiéreRepository $matiéreRepository): Response
    {
        return $this->render('matiére/index.html.twig', [
            'mati_res' => $matiéreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_mati_re_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $matiére = new Matiére();
        $form = $this->createForm(MatiéreType::class, $matiére);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($matiére);
            $entityManager->flush();

            return $this->redirectToRoute('app_mati_re_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('matiére/new.html.twig', [
            'mati_re' => $matiére,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mati_re_show', methods: ['GET'])]
    public function show(Matiére $matiére): Response
    {
        return $this->render('matiére/show.html.twig', [
            'mati_re' => $matiére,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_mati_re_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Matiére $matiére, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MatiéreType::class, $matiére);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_mati_re_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('matiére/edit.html.twig', [
            'mati_re' => $matiére,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mati_re_delete', methods: ['POST'])]
    public function delete(Request $request, Matiére $matiére, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$matiére->getId(), $request->request->get('_token'))) {
            $entityManager->remove($matiére);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_mati_re_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/matiére/_delete_form.html.twig
<form method="post" action="{{ path('app_mati_re_delete', {'id': mati_re.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mati_re.id) }}">
    <button class="btn">Delete</button>
</form>

templates/matiére/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/matiére/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Matiére{% endblock %}

{% block body %}
    <h1>Edit Matiére</h1>

    {{ include('matiére/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mati_re_index') }}">back to list</a>

    {{ include('matiére/_delete_form.html.twig') }}
{% endblock %}

templates/matiére/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matiére index{% endblock %}

{% block body %}
    <h1>Matiére index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_M</th>
                <th>Intitulé</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mati_re in mati_res %}
            <tr>
                <td>{{ mati_re.id }}</td>
                <td>{{ mati_re.idM }}</td>
                <td>{{ mati_re.intitulé }}</td>
                <td>
                    <a href="{{ path('app_mati_re_show', {'id': mati_re.id}) }}">show</a>
                    <a href="{{ path('app_mati_re_edit', {'id': mati_re.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_mati_re_new') }}">Create new</a>
{% endblock %}

templates/matiére/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Matiére{% endblock %}

{% block body %}
    <h1>Create new Matiére</h1>

    {{ include('matiére/_form.html.twig') }}

    <a href="{{ path('app_mati_re_index') }}">back to list</a>
{% endblock %}

templates/matiére/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matiére{% endblock %}

{% block body %}
    <h1>Matiére</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mati_re.id }}</td>
            </tr>
            <tr>
                <th>Id_M</th>
                <td>{{ mati_re.idM }}</td>
            </tr>
            <tr>
                <th>Intitulé</th>
                <td>{{ mati_re.intitulé }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_mati_re_index') }}">back to list</a>

    <a href="{{ path('app_mati_re_edit', {'id': mati_re.id}) }}">edit</a>

    {{ include('matiére/_delete_form.html.twig') }}
{% endblock %}