src/Entity/Enseignant.php
<?php

namespace App\Entity;

use App\Repository\EnseignantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EnseignantRepository::class)]
class Enseignant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_E = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $prenom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdE(): ?int
    {
        return $this->id_E;
    }

    public function setIdE(int $id_E): static
    {
        $this->id_E = $id_E;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }
}

src/Form/EnseignantType.php
<?php

namespace App\Form;

use App\Entity\Enseignant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnseignantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_E')
            ->add('nom')
            ->add('prenom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enseignant::class,
        ]);
    }
}

src/Controller/EnseignantController.php
<?php

namespace App\Controller;

use App\Entity\Enseignant;
use App\Form\EnseignantType;
use App\Repository\EnseignantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/enseignant')]
class EnseignantController extends AbstractController
{
    #[Route('/', name: 'app_enseignant_index', methods: ['GET'])]
    public function index(EnseignantRepository $enseignantRepository): Response
    {
        return $this->render('enseignant/index.html.twig', [
            'enseignants' => $enseignantRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_enseignant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $enseignant = new Enseignant();
        $form = $this->createForm(EnseignantType::class, $enseignant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($enseignant);
            $entityManager->flush();

            return $this->redirectToRoute('app_enseignant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('enseignant/new.html.twig', [
            'enseignant' => $enseignant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enseignant_show', methods: ['GET'])]
    public function show(Enseignant $enseignant): Response
    {
        return $this->render('enseignant/show.html.twig', [
            'enseignant' => $enseignant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_enseignant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Enseignant $enseignant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EnseignantType::class, $enseignant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_enseignant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('enseignant/edit.html.twig', [
            'enseignant' => $enseignant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enseignant_delete', methods: ['POST'])]
    public function delete(Request $request, Enseignant $enseignant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enseignant->getId(), $request->request->get('_token'))) {
            $entityManager->remove($enseignant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_enseignant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/enseignant/_delete_form.html.twig
<form method="post" action="{{ path('app_enseignant_delete', {'id': enseignant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enseignant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/enseignant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/enseignant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Enseignant{% endblock %}

{% block body %}
    <h1>Edit Enseignant</h1>

    {{ include('enseignant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_enseignant_index') }}">back to list</a>

    {{ include('enseignant/_delete_form.html.twig') }}
{% endblock %}

templates/enseignant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enseignant index{% endblock %}

{% block body %}
    <h1>Enseignant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_E</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for enseignant in enseignants %}
            <tr>
                <td>{{ enseignant.id }}</td>
                <td>{{ enseignant.idE }}</td>
                <td>{{ enseignant.nom }}</td>
                <td>{{ enseignant.prenom }}</td>
                <td>
                    <a href="{{ path('app_enseignant_show', {'id': enseignant.id}) }}">show</a>
                    <a href="{{ path('app_enseignant_edit', {'id': enseignant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_enseignant_new') }}">Create new</a>
{% endblock %}

templates/enseignant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Enseignant{% endblock %}

{% block body %}
    <h1>Create new Enseignant</h1>

    {{ include('enseignant/_form.html.twig') }}

    <a href="{{ path('app_enseignant_index') }}">back to list</a>
{% endblock %}

templates/enseignant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enseignant{% endblock %}

{% block body %}
    <h1>Enseignant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enseignant.id }}</td>
            </tr>
            <tr>
                <th>Id_E</th>
                <td>{{ enseignant.idE }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ enseignant.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ enseignant.prenom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_enseignant_index') }}">back to list</a>

    <a href="{{ path('app_enseignant_edit', {'id': enseignant.id}) }}">edit</a>

    {{ include('enseignant/_delete_form.html.twig') }}
{% endblock %}